// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBotsWithKnowledge = "bots_with_knowledge"

// BotsWithKnowledge mapped from table <bots_with_knowledge>
type BotsWithKnowledge struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:机器人初始设置ID" json:"id"`            // 机器人初始设置ID
	BotID       int64     `gorm:"column:bot_id;not null;comment:机器人ID 关联 bots.id" json:"bot_id"`                  // 机器人ID 关联 bots.id
	KnowledgeID int64     `gorm:"column:knowledge_id;not null;comment:知识库ID 关联 knowledge.id" json:"knowledge_id"` // 知识库ID 关联 knowledge.id
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`     // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`     // 更新时间
}

// TableName BotsWithKnowledge's table name
func (*BotsWithKnowledge) TableName() string {
	return TableNameBotsWithKnowledge
}
