// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBot = "bots"

// Bot mapped from table <bots>
type Bot struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:机器人ID" json:"id"`            // 机器人ID
	Name      string    `gorm:"column:name;not null;comment:机器人名称" json:"name"`                             // 机器人名称
	Avatar    string    `gorm:"column:avatar;not null;comment:机器人头像" json:"avatar"`                         // 机器人头像
	Desc      string    `gorm:"column:desc;not null;comment:机器人描述" json:"desc"`                             // 机器人描述
	UserID    int64     `gorm:"column:user_id;not null;comment:创建人用户ID 关联 user.id" json:"user_id"`          // 创建人用户ID 关联 user.id
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Bot's table name
func (*Bot) TableName() string {
	return TableNameBot
}
