// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePromptConfig = "prompt_config"

// PromptConfig mapped from table <prompt_config>
type PromptConfig struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户全局唯一主键" json:"id"`         // 用户全局唯一主键
	Key       string    `gorm:"column:key;not null;comment:prompt 关键词" json:"key"`                          // prompt 关键词
	Value     string    `gorm:"column:value;not null;comment:prompt 详细文本" json:"value"`                     // prompt 详细文本
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName PromptConfig's table name
func (*PromptConfig) TableName() string {
	return TableNamePromptConfig
}
