// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	promptConfigFieldNames          = builder.RawFieldNames(&PromptConfig{})
	promptConfigRows                = strings.Join(promptConfigFieldNames, ",")
	promptConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(promptConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	promptConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(promptConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePromptConfigIdPrefix = "cache:promptConfig:id:"
)

type (
	promptConfigModel interface {
		Insert(ctx context.Context, data *PromptConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PromptConfig, error)
		Update(ctx context.Context, data *PromptConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPromptConfigModel struct {
		sqlc.CachedConn
		table string
	}

	PromptConfig struct {
		Id        int64     `db:"id"`
		Key       string    `db:"key"`   // prompt 关键词
		Value     string    `db:"value"` // prompt 详细文本
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newPromptConfigModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPromptConfigModel {
	return &defaultPromptConfigModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`prompt_config`",
	}
}

func (m *defaultPromptConfigModel) Delete(ctx context.Context, id int64) error {
	promptConfigIdKey := fmt.Sprintf("%s%v", cachePromptConfigIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, promptConfigIdKey)
	return err
}

func (m *defaultPromptConfigModel) FindOne(ctx context.Context, id int64) (*PromptConfig, error) {
	promptConfigIdKey := fmt.Sprintf("%s%v", cachePromptConfigIdPrefix, id)
	var resp PromptConfig
	err := m.QueryRowCtx(ctx, &resp, promptConfigIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promptConfigRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPromptConfigModel) Insert(ctx context.Context, data *PromptConfig) (sql.Result, error) {
	promptConfigIdKey := fmt.Sprintf("%s%v", cachePromptConfigIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, promptConfigRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Key, data.Value)
	}, promptConfigIdKey)
	return ret, err
}

func (m *defaultPromptConfigModel) Update(ctx context.Context, data *PromptConfig) error {
	promptConfigIdKey := fmt.Sprintf("%s%v", cachePromptConfigIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, promptConfigRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Key, data.Value, data.Id)
	}, promptConfigIdKey)
	return err
}

func (m *defaultPromptConfigModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePromptConfigIdPrefix, primary)
}

func (m *defaultPromptConfigModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", promptConfigRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPromptConfigModel) tableName() string {
	return m.table
}
