// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户全局唯一主键" json:"id"`         // 用户全局唯一主键
	Name      string    `gorm:"column:name;not null;comment:用户名称" json:"name"`                              // 用户名称
	Email     string    `gorm:"column:email;not null;comment:用户邮箱" json:"email"`                            // 用户邮箱
	Password  string    `gorm:"column:password;not null;comment:用户密码" json:"password"`                      // 用户密码
	Avatar    string    `gorm:"column:avatar;not null;comment:用户头像" json:"avatar"`                          // 用户头像
	IsAdmin   bool      `gorm:"column:is_admin;comment:是否为管理员" json:"is_admin"`                             // 是否为管理员
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
